### ISSUE TITLE
Для всех упражнений

### ISSUE THREAD

**Issue by slemeshevsky** [sava1561/pyTasks#1]
Во всех файлах проблема с кодировкой. Я понимаю, что все делалось в PyCharm, но, вообще говоря, сценарии python должны работать не только в IDE, а нормально обрабатываться интерпретатором. А когда в файле указано, что он имеет кодировку utf-8 а на самом деле сохранен в кодировке Windows, то проблемы с выполнением такого сценария обязательно будут.

Вот пример
`python3 rectangle_area_func.py `
`  File "rectangle_area_func.py", line 5`
`SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte`

Пока я буду зачитывать такие задания. Правда мне придется перекодировать файлы в кодировку utf-8, но с этим надо разобраться.

**Comment by sava1561** [comment]
Исправлю ,спасибо,что сказали

**Comment by sava1561** [comment]
Исправил в ch_2
