### ISSUE TITLE
Упражнение 2.11

### ISSUE THREAD

**Issue by slemeshevsky** [sava1561/pyTasks#2]
Странное поведение графиков. Да и точность плохая. И файл в другой папке лежит.
![pi_computing](https://cloud.githubusercontent.com/assets/4579135/21092815/a6681fa6-c05f-11e6-8d94-d11c4a114078.png)

**Comment by sava1561** [comment]
Это может зависеть от версии питона?
![image](https://cloud.githubusercontent.com/assets/24411386/21093988/c5a4b36a-c065-11e6-91f3-4c417c0ab325.png)

**Comment by slemeshevsky** [comment]
Это, конечно, странно. Да и файл сейчас из репозитария пропал

**Comment by sava1561** [comment]
перезакинул в ch_2

**Comment by slemeshevsky** [comment]
Да от версии зависит. Но это не правильно. Я считаю, что вычисления не должны зависеть от версии python. Я не думаю, что исправить сценарий - это большая проблема.

**Comment by sava1561** [comment]
Возможно исправил(не могу проверить)
