### ISSUE TITLE
Упражнение 2.12

### ISSUE THREAD

**Issue by slemeshevsky** [sava1561/pyTasks#3]
Совсем не понимаю, что делает сценарий. Просто выводит одно число. Комментарии вообще не читаемые, даже в github :-(
[combine_sets.py](https://github.com/sava1561/pyTasks/blob/master/ch_2/combine_sets.py)

**Comment by sava1561** [comment]
Надеюсь исправил

**Comment by sava1561** [comment]
Исправил
